### ISSUE TITLE
Check here for why downloads count not used in criticality score.

### ISSUE THREAD

**Issue by kof** [ossf/criticality_score#18]
I think downloads count have a serious role here as well because it shows the actual size of the audience who depends on the package. Imagine a very popular project depends on project X. For project X it's only one dependant, but the dependant project has criticality of 1 with millions of downloads. Making this project also much more important than it is in isolation.

**Comment by inferno-chromium** [comment]
As much as i wish to add that, that data point is not actionable and is not available for most repos. You can add it via --params param when available, but since we dont have that information for most repos, we are not using in the top ranking calculation.

**Comment by tgamblin** [comment]
FWIW, even through GitHub's web stats (which are not public), the clone count is very strongly affected by the type and amount of CI the project has.  We stopped advertising this metric for Spack (https://github.com/spack/spack) because the numbers didn't make sense -- we're prett sure we have far more CI clones than human ones.

As @inferno-chromium mentioned, downloads of release artifacts are also hard to track.  If you upload an artifact to a GitHub release, GitHub tracks downloads and you can see them via the API.  However, they do not track downloads for the auto-generated .tar.gz and .zip links, which are still present even if you upload a release artifact, so it's very hard to track downloads of any sort even if you have all the information available from GitHub.

**Comment by kof** [comment]
If I would create a fork and try to incorporate downloads, how would you fit it in in the formula?

**Comment by inferno-chromium** [comment]
> If I would create a fork and try to incorporate downloads, how would you fit it in in the formula?

you can already do this via the --params command line arg, probably with a 1-2 factor weight, and pick some max threshold.
