### ISSUE TITLE
How are the top 200 lists calculated?

### ISSUE THREAD

**Issue by tgamblin** [ossf/criticality_score#32]
Curious how the top200 lists are calculated -- or at least how particular language projects come to be included.  Spack (https://github.com/spack/spack) has a score (.78779) that would put it at # 17 in the current Python list, and GitHub says it's a Python project.  But it's not in the generated `.csv` at all.  Conda (https://github.com/conda/conda, with a score of .71509) also does not appear.

**Comment by inferno-chromium** [comment]
Basically, we get a list of 1000 repos sorted by stars (descending) and then run criticality score to sort then again. This is not sufficient and currently hitting a github search api limitation, we do plan to explore other ways to expand sample set so that these project show up properly. Tracking in https://github.com/ossf/criticality_score/issues/33
